const gFaces = ['<i class="fa-light fa-face-awesome"></i>',
    '<i class="fa-solid fa-face-woozy"></i>',
    '<i class="fa-solid fa-face-worried"></i>',
    '<i class="fa-solid fa-face-smiling-hands"></i>',
    '<i class="fa-solid fa-face-zany"></i>',
    '<i class="fa-solid fa-face-tired"></i>',
    '<i class="fa-solid fa-face-sad-cry"></i>',
    '<i class="fa-solid fa-face-sleeping"></i>',
    '<i class="fa-solid fa-face-rolling-eyes"></i>',
    '<i class="fa-solid fa-face-monocle"></i>',
    '<i class="fa-solid fa-face-grin-tears"></i>',
    '<i class="fa-solid fa-face-hand-yawn"></i>',
    '<i class="fa-solid fa-face-angry-horns"></i>',
    '<i class="fa-solid fa-face-grin-beam-sweat"></i>',
    '<i class="fa-solid fa-face-head-bandage"></i>',
    '<i class="fa-solid fa-face-dizzy"></i>']